問題2より後を表示したい
Yoshi-purple/JSwork_4 pull request #1
Opened 2021-01-26 07:03 UTC by Yoshi-purple

エラーは出ておりません。
・やりたいこと
=>問題2で回答ボタンをクリックした際に問題3へ移行したい
・試したこと
=>問題1が表示された後に、
class属性で改めてボタンの要素を取得するコードをいくつか試しましたが、反応がなく、エラーも出ません
一度コードを見ていただいてもよろしいでしょうか。
よろしくお願いします。

2021-01-27 10:14 UTC, Yoshi-purple commented
JS課題4のクイズアプリを実装しましたので、
コードレビューをお願いします！

2021-01-27 13:45 UTC, myzktkyk requested changes
動作は仕様として明示されているものについては問題ありませんでした。
コードは何点か指摘があります。

あと、欲を言うと…現状、選択肢の4つ目が常に正解になってしまっていて
クイズアプリとしては面白みに欠けてしまいます。
選択肢をシャッフルするようにしてみてください。

2021-01-27 13:45 UTC, myzktkyk commented on app.js
> +  });
非同期処理を呼び出す場合は `await` を使う必要があり
`await` を利用する場合は呼び出しを行う関数に `async` が必要です。

```suggestion
  btnStart.addEventListener('click', async () => {
    await getQuiz(val);
  });
```

2021-01-27 13:45 UTC, myzktkyk commented on app.js
> +  }
`Promise` でも問題はないのですが…せっかく `async` `await` を使うならこのようにするとよりよいかと思いました。
```suggestion
  async function getQuiz(val) {
    head.textContent = '取得中';
    question.textContent = '少々お待ちください。';
    btnsDiv.removeChild(btnStart);
    await callAPI(val);
  }
```

2021-01-27 13:45 UTC, myzktkyk commented on app.js
> +    );
API の呼び出しはネットワークエラーなど予期しない例外が起こることが想定されるので
基本的に `try/catch` をしておきましょう。

```suggestion
    let response;
    try {
      response = await fetch('https://opentdb.com/api.php?amount=10&type=multiple');
    } catch (e) {
      console.error(e);
    }
```

2021-01-28 20:12 UTC, Yoshi-purple commented
JS課題4のクイズアプリを実装しました。
ご指摘いただいたコードの変更、
回答ボタンのランダム表示を実装しました！
コードレビューをお願いします！

2021-01-31 00:44 UTC, Yoshi-purple commented
JS課題4のクイズアプリを修正しましたので、
コードレビューをお願いします！

2021-01-31 08:51 UTC, Yoshi-purple commented
↑に更に修正を加えました。
JS課題4のクイズアプリを実装しましたので、
コードレビューをお願いします！

2021-02-01 13:04 UTC, Yoshi-purple commented
undifinedとなっていたところの修正をしましたので、
コードレビューをお願いします！

2021-03-28 19:27 UTC, merged